Task 1: implemented Inventory Create DAO and testing
KRB065/fullstack-starter pull request #1
Opened 2022-07-28 04:07 UTC by KRB065

2022-07-30 01:36 UTC, ohnoitsyou requested changes

2022-07-30 01:36 UTC, ohnoitsyou commented on starter/src/test/java/com/starter/fullstack/dao/InventoryDAOTest.java
> +    System.out.println("After Create Method ID: " + inventory1.getId());
Part of testing is also verifying that after you run the method under test, `create` in this case, by using `assert`s

2022-07-30 01:36 UTC, ohnoitsyou commented on starter/src/test/java/com/starter/fullstack/dao/InventoryDAOTest.java
> +    inventory1.setId("877241");
Try using the ID that's defined as a constant from up above

2022-08-01 22:36 UTC, KRB065 reviewed
Added assert statement

2022-08-05 20:49 UTC, ohnoitsyou requested changes

2022-08-05 20:49 UTC, ohnoitsyou commented on starter/target/surefire-reports/com.starter.fullstack.dao.InventoryDAOTest.txt
> +
Take a look at this test and see why it's failing.

You should also not include the test report in the repository.

2022-08-05 20:49 UTC, ohnoitsyou commented on starter/target/surefire-reports/com.starter.fullstack.dao.ProductDAOTest.txt
> +Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.349 s - in com.starter.fullstack.dao.ProductDAOTest
Please remove the test report.

2022-08-05 20:49 UTC, ohnoitsyou commented on starter/target/surefire-reports/com.starter.fullstack.rest.ProductControllerTest.txt
> +Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.475 s - in com.starter.fullstack.rest.ProductControllerTest
Please remove the test report.

2022-08-05 20:49 UTC, ohnoitsyou commented on starter/src/test/java/com/starter/fullstack/dao/InventoryDAOTest.java
> +    Assert.assertTrue(inventory1.getId() != "877241");
This is part of the reason you should use the variables you have defined at the class level. Although the contents of the strings are the same, they are technically two different strings. You should use a variable in both the creation of the item and the checking of the item.

2022-08-05 20:49 UTC, ohnoitsyou commented on starter/.gitignore
> +*.jar
Although not a huge deal, you have some duplicates.

2022-08-08 02:43 UTC, closed without merging