Task4 delete inventory controller
KRB065/fullstack-starter pull request #6
Opened 2022-09-09 22:19 UTC by KRB065

Created delete functionality to the inventory controller

2022-09-13 01:05 UTC, ohnoitsyou requested changes

2022-09-13 01:05 UTC, ohnoitsyou commented on starter/src/main/java/com/starter/fullstack/rest/InventoryController.java
> +    System.out.println("ID = " + id);
Go ahead and remove the print statement.

2022-09-15 19:50 UTC, lndyaouie commented on starter/src/main/java/com/starter/fullstack/rest/InventoryController.java
> +  @DeleteMapping()
I would remove the parentheses here.

2022-09-15 19:52 UTC, lndyaouie commented on starter/src/main/java/com/starter/fullstack/rest/InventoryController.java
> +  @DeleteMapping()
I would remove the parentheses here since it adds nothing.

2022-10-03 17:44 UTC, merged